yarnPath: .yarn/releases/yarn-3.5.1.cjs
nodeLinker: 'pnp'
packageExtensions:
  debug@*:
    dependencies:
      supports-color: '*'
  '@vitejs/plugin-react@*':
    dependencies:
      vite: '*'
  '@vanilla-extract/vite-plugin@*':
    dependencies:
      vite: '*'
  vite@*:
    dependencies:
      supports-color: '*'
